# Generated by Django 4.2.6 on 2023-10-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('address', models.TextField()),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(max_length=6)),
                ('dob', models.CharField(blank=True, max_length=10, null=True, verbose_name='Date of Birth')),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
